(() => {
  const trToEn = new Map(Object.entries({
    'Bir fikir.':'One idea.','Eksiksiz bir e-kitap.':'A complete ebook.','Bir fikir. Eksiksiz bir e-kitap.':'One idea. A complete ebook.','Nasıl çalışır?':'How it works','Özellikler':'Features','Fiyatlar':'Pricing','Giriş yap':'Log in','Ücretsiz başla':'Start free',
    'Yapay zekâ destekli yeni nesil yayın stüdyosu':'The next-generation AI publishing studio',
    'Bir cümleyle başla. Yapay zekâ bölümleri, kapak tasarımını ve satışa hazır dosyanı seninle birlikte oluştursun.':'Start with one sentence. AI creates the chapters, cover design, and publication-ready file with you.',
    'İlk dijital ürününü satma rehberi':'A guide to selling your first digital product','Çocuklar için doğa boyama kitabı':'A nature coloring book for children','Freelance çalışanlar için fiyatlandırma':'Pricing for freelancers',
    'Kart gerekmez · İstediğin zaman iptal et · Ticari kullanım hakkı sende':'No card required · Cancel anytime · You keep commercial rights',
    'Ürünlerini burada satmaya hazırla':'Prepare your products to sell here','SONUCU ÖNCEDEN GÖR':'PREVIEW THE RESULT','Bir fikirden,':'From one idea,','gerçek bir kitaba.':'to a real book.',
    'Ebookera yalnızca metin üretmez. Başlığı, içindekiler yapısını, kapak yönünü ve satışa hazır sayfa düzenini birlikte kurar.':'Ebookera does more than generate text. It creates the title, structure, cover direction, and sales-ready page system together.',
    'Kapak, tipografi ve içerik aynı yaratıcı sistemden çıkar.':'Cover, typography, and content emerge from one creative system.','Okuyucu karşısına çıktığında “AI metni” değil, editoryal olarak tasarlanmış bir dijital ürün görür.':'Your reader sees an editorially designed digital product, not raw AI text.','Kapak':'Cover','İç sayfa':'Inside page',
    'Fikrinden':'Turn ideas into a','katalog':'catalog','yarat.':'of products.','Her fikir, yazım kararlarını sana bırakan; kapağı ve satış dosyasıyla tamamlanan küçük bir dijital ürüne dönüşür.':'Every idea becomes a focused digital product, complete with your writing decisions, cover, and sales file.','fikir':'idea','bölüme kadar':'chapters max','ürün':'product',
    'Ebookera asistan':'Ebookera assistant','canlı üretim':'live generation','ŞİMDİ YAZILIYOR':'WRITING NOW','tamamlandı':'complete','yazılıyor':'writing','Satışa hazır':'Ready to sell','Boyama kitabı':'Coloring book','24 baskı sayfası':'24 print pages',
    'NASIL ÇALIŞIR?':'HOW IT WORKS','Fikirden vitrine, üç kısa adım.':'From idea to storefront in three short steps.','Fikrini anlat':'Describe your idea','Ne bildiğini, kim için yazdığını bir iki cümleyle söyle.':'Tell us what you know and who you are writing for in one or two sentences.','≈ 1 dakika':'≈ 1 minute','Birlikte şekillendir':'Shape it together','Başlığı, bölüm planını, kapak yönünü ve yazım tonunu onayla.':'Approve the title, chapter plan, cover direction, and writing tone.','Kontrol tamamen sende':'You stay in control','İndir ve sat':'Download and sell','Düzenlenmiş kitabını mağazana yüklemeye hazır olarak al.':'Get a formatted ebook ready to upload to your store.',
    'AMACINA UYGUN FORMAT':'THE RIGHT FORMAT','Her fikir aynı':'Not every idea','kitaba dönüşmez.':'becomes the same book.','Hedefine göre uzunluk, yapı ve sayfa sistemini seç. Ebookera üretim planını buna göre kursun.':'Choose the length, structure, and page system for your goal. Ebookera builds the production plan around it.','Hızlı rehber':'Quick guide','Tek bir problemi çözen, kolay tüketilen dijital ürün.':'An easy-to-consume digital product that solves one problem.','Çalışma kitabı':'Workbook','Egzersizler, kontrol listeleri ve uygulanabilir şablonlar.':'Exercises, checklists, and practical templates.','Otorite raporu':'Authority report','Uzmanlığını sistemli ve güven veren bir yayına dönüştür.':'Turn your expertise into a structured, credible publication.','Tutarlı görsel dünya ve baskıya uygun çizgi sayfaları.':'A consistent visual world and print-ready line art.',
    'BASİT FİYATLANDIRMA':'SIMPLE PRICING','İlk fikrin ücretsiz.':'Your first idea is free.','Yayınlamaya hazır olduğunda paketi seçersin.':'Choose a plan when you are ready to publish.','LANSMAN PAKETİ':'LAUNCH PLAN','Üretici':'Creator','Her ay yeni ürünler çıkaranlar için.':'For creators launching new products every month.','/ ay':'/ month','Üretmeye başla':'Start creating','250 üretim kredisi':'250 generation credits','PDF, EPUB ve DOCX dışa aktarımı':'PDF, EPUB, and DOCX export','Ticari kullanım lisansı':'Commercial-use license',
    'SIK SORULANLAR':'FAQ','Aklında kalanlar.':'What you may be wondering.','Ebookera, ChatGPT’den nasıl farklı?':'How is Ebookera different from ChatGPT?','Ürettiğim kitabı satabilir miyim?':'Can I sell the ebook I create?','Üretim ne kadar sürer?':'How long does generation take?','Hangi mağazalara yükleyebilirim?':'Which stores can I use?',
    'KREDİLER':'CREDITS','kullanılabilir':'available','Ücretsiz plan':'Free plan','Pro’ya geç':'Upgrade to Pro','Pro’ya geç →':'Upgrade →','Kontrol paneli':'Dashboard','e‑Kitap oluştur':'Create ebook','Kitaplarım':'My ebooks','Tasarım stüdyosu':'Design studio','YAKINDA':'SOON','Senin stüdyon':'Your studio','Üretmeye devam et':'Keep creating','Çıkış yap':'Sign out',
    'Merhaba, üretmeye hazır mısın?':'Ready to create?','Bugün bir fikirden yeni bir dijital ürün çıkarabilirsin.':'Turn one idea into a new digital product today.','Toplam kitap':'Total ebooks','Oluşturulan bölüm':'Chapters created','Yazılan kelime':'Words written','Son projeler':'Recent projects','+ Yeni proje':'+ New project','Yeni proje':'New project','Sıfırdan başla':'Start from scratch',
    'YENİ E‑KİTAP':'NEW EBOOK','Fikir':'Idea','Format':'Format','Başlık':'Title','Plan':'Plan','AI yayın asistanın':'Your AI publishing assistant','fikrini dinliyor':'listening to your idea','Merhaba, kitabını birlikte yapalım.':'Hi, let’s create your ebook.','Konunu bir iki cümleyle anlat. Formatı, dili ve uzunluğu birlikte belirleyip sana yayınlanabilir bir kitap planı çıkaracağım.':'Describe your topic in one or two sentences. We will choose the format, language, and length, then build a publication-ready plan.','Daha iyi sonuç için detay ekle':'Add detail for better results','Fikrin planlanmaya hazır':'Your idea is ready to plan','✦ Bir örnek göster':'✦ Show an example','⌁ Fikir seçmeme yardım et':'⌁ Help me choose an idea','YAYIN AYARLARI':'PUBLISHING SETTINGS','Kitabının dilini, yapısını ve hedef uzunluğunu seç.':'Choose your ebook language, structure, and target length.','Kitap formatı':'Ebook format','Dil':'Language','Kitap uzunluğu':'Ebook length','Yazım tonu':'Writing tone','Planımı hazırla':'Create my plan','Ücretsiz model yoğunluğuna göre planın hazırlanması 20–60 saniye sürebilir.':'Planning may take 20–60 seconds depending on free-model availability.',
    'Pratik rehber':'Practical guide','Hikâye / kurgu':'Story / fiction','Eğitim materyali':'Learning material','Standart · 12 bölüm':'Standard · 12 chapters','Detaylı · 18 bölüm':'Detailed · 18 chapters','Uzun · 24 bölüm':'Long · 24 chapters','Samimi ve güven veren':'Warm and reassuring','Profesyonel':'Professional','Enerjik ve cesur':'Energetic and bold','Minimal ve doğrudan':'Minimal and direct',
    'Fikri ve formatı düzenle':'Edit idea and format','BAŞLIK + PLAN':'TITLE + OUTLINE','BAŞLIĞINI SEÇ':'CHOOSE YOUR TITLE','Fikrinden doğan kitap':'Your ebook concept','Yayınlayacağın başlığı seç veya kendi başlığını düzenle.':'Choose the title you will publish under or write your own.','✎ Kendi başlığımı yaz':'✎ Write my own title','↻ 3 yeni başlık göster':'↻ Show 3 new titles','1 kredi':'1 credit','BÖLÜM PLANI':'CHAPTER OUTLINE','Bölümleri düzenleyebilir veya yeni bölüm ekleyebilirsin.':'Edit chapters or add a new one.','+ Bölüm ekle':'+ Add chapter','KAPAK YÖNÜ':'COVER DIRECTION','Kitabının mağazada nasıl hissedileceğini seç.':'Choose how your ebook should feel in the storefront.','Editoryal':'Editorial','Güçlü tipografi':'Strong typography','Sıcak':'Warm','Samimi ve doğal':'Friendly and natural','Cesur':'Bold','Yüksek kontrast':'High contrast',
    'Plan inceleniyor':'Reviewing plan','Ebookera kitabını hazırlıyor':'Ebookera is creating your ebook','Ebookera Asistan':'Ebookera Assistant','kitabın üzerinde çalışıyor':'working on your ebook','Planı düzenle':'Edit plan','Ebookera çalışıyor…':'Ebookera is working…','KİTAPLIĞIN':'YOUR LIBRARY','Ürettiğin işler':'Your creations','Projelerini görüntüle ve satışa hazır dosyalarını indir.':'View your projects and download sales-ready files.','İlk kitabın burada görünecek.':'Your first ebook will appear here.','Bir fikirle başla; Ebookera planı, kapağı ve içeriği birlikte hazırlasın.':'Start with one idea and let Ebookera create the plan, cover, and content together.','İlk kitabımı oluştur':'Create my first ebook',
    'Bir sonraki':'Your next','kitabın burada.':'ebook starts here.','Fikrini kaybetme; kitaplığın, taslakların ve indirmelerin tek yerde kalsın.':'Keep your ideas, drafts, library, and downloads in one place.','STÜDYONA HOŞ GELDİN':'WELCOME TO YOUR STUDIO','Giriş yap veya hesabını birkaç saniyede oluştur.':'Log in or create your account in seconds.','Google ile devam et':'Continue with Google','ve e-posta ile':'or use email','E-posta adresin':'Email address','Şifren':'Password','Giriş yap / hesap oluştur':'Log in / create account','Devam ederek':'By continuing, you agree to the','Kullanım Koşulları':'Terms of Use','Gizlilik Politikası':'Privacy Policy',
    'Sohbet içinde ham metin bırakmak yerine plan, bölümler, kapak yönü ve baskıya uygun sayfa düzenini tek bir proje olarak üretir.':'Instead of leaving raw text in a chat, Ebookera creates the outline, chapters, cover direction, and print-ready layout as one project.','Evet. Kendi girdiğin fikir ve ürettiğin çalışma için ticari kullanım hakkı sende kalır. Yayınlamadan önce içeriği doğrulaman ve düzenlemen gerekir.':'Yes. You keep commercial rights to your idea and generated work. Review and edit the content before publishing.','Ücretsiz model yoğunluğuna göre değişir. Plan genellikle bir dakikanın altında, tam kitap ise bölüm sayısına bağlı olarak birkaç dakika içinde hazırlanır.':'Timing depends on free-model availability. Plans usually take under a minute; complete ebooks take a few minutes depending on chapter count.','PDF çıktısını Etsy, Shopier ve Gumroad’da; uygun ölçülerdeki kitaplarını Amazon KDP’de kullanabilirsin.':'Use PDF exports on Etsy, Shopier, and Gumroad, and properly formatted books on Amazon KDP.',
    '◌ BASKIYA UYGUN BOYAMA KİTABI':'◌ PRINT-READY COLORING BOOK','Renklendirecek':'Create a world','bir dünya kur.':'to color.','Fikrini ve tarzını seç. Ebookera sayfaları planlasın, her bir çizimi baskıya uygun hazırlasın.':'Choose your idea and style. Ebookera plans the pages and prepares every illustration for print.','Boyama kitabın ne hakkında?':'What is your coloring book about?','Çizim tarzı':'Illustration style','Sayfa sayısı':'Page count','Tekrarlayan karakterleri koru':'Keep recurring characters','✦ Sayfa planını oluştur':'✦ Create page plan','kredi':'credits','Hazır':'Ready','Taslak':'Draft','bölüm':'chapters'
  }));
  const placeholders = new Map([
    ['Örn. Yeni başlayanlar için evde kahve demleme rehberi','e.g. A home coffee brewing guide for beginners'],
    ['Örn. Serbest çalışan tasarımcılar için müşteri bulma ve fiyat belirleme rehberi','e.g. A client acquisition and pricing guide for freelance designers'],
    ['ornek@eposta.com','name@email.com']
  ]);
  let lang = localStorage.getItem('ebookera-ui-language') || 'tr';
  function translate(root = document.body) {
    document.documentElement.lang = lang;
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
    let node;
    while ((node = walker.nextNode())) {
      if (node.__ebookeraTr === undefined) node.__ebookeraTr = node.nodeValue;
      const original = node.__ebookeraTr; const key = original.trim(); const replacement = lang === 'en' ? trToEn.get(key) : key;
      node.nodeValue = replacement ? original.replace(key, replacement) : original;
    }
    root.querySelectorAll?.('[placeholder]').forEach(element => {
      element.dataset.trPlaceholder ||= element.getAttribute('placeholder');
      element.setAttribute('placeholder', lang === 'en' ? placeholders.get(element.dataset.trPlaceholder) || element.dataset.trPlaceholder : element.dataset.trPlaceholder);
    });
    document.querySelectorAll('[data-ui-lang]').forEach(button => button.classList.toggle('active', button.dataset.uiLang === lang));
  }
  function setLanguage(next) {
    lang = next === 'en' ? 'en' : 'tr'; localStorage.setItem('ebookera-ui-language', lang); translate();
    window.dispatchEvent(new CustomEvent('ebookera:language', { detail: { language: lang } }));
  }
  document.querySelectorAll('[data-ui-lang]').forEach(button => button.addEventListener('click', () => setLanguage(button.dataset.uiLang)));
  window.EbookeraI18n = { get lang() { return lang; }, translate, setLanguage };
  translate();
})();
